### PR TITLE
Add ability to load assets from gems

### PR DESCRIPTION
**Pull request by lsylvester**
This adds the ability to configure asset load paths from gems.

Add to `.blade.yml`

gem_paths:
  gem_name:
    - path/to/include
    - other/path/to/include

### CODE REVIEW

**Comment by javan** [comment]
I can see how this would be useful, but I think it would be more clear to put under the `load_paths` config, possible as a hash:
```yaml
load_paths:
  - src
  - { gem: ..., load_paths: [...] }
```
What do you think?

**Comment by javan** [comment]
Or maybe:
```yaml
load_paths:
  - src
  - { gemName: [paths] }
```

**Comment by lsylvester** [comment]
@javan I have updated to use the syntax

```yaml
load_paths:
  - src
  - { gemName: [paths] }
```
to load paths from the gems

**Comment by javan** [comment]
Thanks!

**Pull request merged**
